src/Entity/Frise.php
<?php

namespace App\Entity;

use App\Repository\FriseRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FriseRepository::class)
 */
class Frise
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $contenu;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $lien;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $id_div;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity=Classe::class, inversedBy="frises")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_classe;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(?string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getLien(): ?string
    {
        return $this->lien;
    }

    public function setLien(?string $lien): self
    {
        $this->lien = $lien;

        return $this;
    }

    public function getIdDiv(): ?string
    {
        return $this->id_div;
    }

    public function setIdDiv(string $id_div): self
    {
        $this->id_div = $id_div;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getIdClasse(): ?Classe
    {
        return $this->id_classe;
    }

    public function setIdClasse(?Classe $id_classe): self
    {
        $this->id_classe = $id_classe;

        return $this;
    }
}

src/Form/FriseType.php
<?php

namespace App\Form;

use App\Entity\Frise;
use App\Entity\Classe;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;



class FriseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date',DateType::class, [
                'widget' => 'single_text',
                'input_format' => 'd/M/Y'
            ])
            ->add('nom',TextType::class)
            ->add('id_classe',EntityType::class, [
                'class' => Classe::class,
                'choice_label' => 'nom',
                'label' => 'Catégorie'
            ])
            ->add('id_div',TextType::class,[
                'label' => 'Div'
            ])

            ->add('lien',FileType::class,[
                'required' => false,
                'data_class' => null,
                'label' => 'Image (.PNG, .JPEG, .GIF, .SVG file)',
                'constraints' => [
                    new File([
                        'maxSize' => '512k',
                        'mimeTypes' => [
                            'image/*',
                        ],
                    ])
                ],
            ])
            ->add('contenu',TextareaType::class,[
                'required' => false,
                'attr' => ['rows'=>'10']
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Envoyer'
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Frise::class,
        ]);
    }
}

src/Controller/FriseController.php
<?php

namespace App\Controller;

use App\Entity\Frise;
use App\Form\FriseType;
use App\Repository\FriseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

/**
 * @Route("/frise")
 */
class FriseController extends AbstractController
{
    /**
     * @Route("/liste", name="listefrise")
     */
    public function index(FriseRepository $friseRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $date = time();

        // affichage de l'entièreté des entité de la liste
        return $this->render('frise/index.html.twig', [
            'frises' => $friseRepository->getByOrder(),
            'titre' => 'Liste des informations de la frise',
            'date' => $date
        ]);
    }

    /**
     * @Route("/ajout", name="ajoutfrise")
     */
    public function new(Request $request, SluggerInterface $slugger): Response
    {
        // création d'une nouvelle entité
        $frise = new Frise();
        // création du formulaire lié à la frise
        $form = $this->createForm(FriseType::class, $frise);
        $form->handleRequest($request);

        // si le formulaire est conforme
        if ($form->isSubmitted() && $form->isValid()) {
            $lienFile = $form->get('lien')->getData();
            if (!empty($lienFile)) {
                $originalFilename = pathinfo($lienFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = 'img/Frise/'.$safeFilename.'-'.uniqid().'.'.$lienFile->guessExtension();
                try {
                    $lienFile->move(
                        $this->getParameter('imgFrise_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash('error', 'Le mouvement a échoué !');
                    return $this->redirectToRoute('accueil');
                }
                $frise->setLien($newFilename);
            }
            $entityManager = $this->getDoctrine()->getManager();
            // mise en place de la requête indiquant que la donnée selectionnée doit être ajouté
            $entityManager->persist($frise);
            // exécution de la requête de "insert"
            $entityManager->flush();
            $this->addFlash('success', 'Un élément a bien été ajouté dans la liste !');

            // Retour liste frise
            return $this->redirectToRoute('listefrise', [], Response::HTTP_SEE_OTHER);
        }
        elseif($form->isSubmitted()){
            $this->addFlash('error', 'Une erreur c\'est produite !');
        }

        // affichage du formulaire
        return $this->renderForm('commun/new.html.twig', [
            'frise' => $frise,
            'form' => $form,
            'titre' => 'Ajout dans la frise'

        ]);
    }

    /**
     * @Route("/detail/{id}", name="detailfrise")
     */
    /*public function show(Frise $frise): Response
    {
        return $this->render('frise/show.html.twig', [
            'frise' => $frise,
            'titre' => 'Détail'
        ]);
    }*/

    /**
     * @Route("/modif/{id}", name="modiffrise")
     */
    public function edit(Request $request, Frise $frise, SluggerInterface $slugger): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $oldFile = basename($frise->getLien());
        // création du formulaire lié à la frise
        $form = $this->createForm(FriseType::class, $frise);

        $form->handleRequest($request);

        // si le formulaire est conforme
        if ($form->isSubmitted() && $form->isValid()) {
            // mise en place et execusion de la requete de "update"
            $lienFile = $form->get('lien')->getData();
            if (!empty($lienFile)) {
                $originalFilename = pathinfo($lienFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = 'img/Frise/'.$safeFilename.'-'.uniqid().'.'.$lienFile->guessExtension();

                try {
                    $lienFile->move(
                        $this->getParameter('imgFrise_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    $this->addFlash('error', 'Le mouvement a échoué !');
                    return $this->redirectToRoute('accueil');
                }

                if(!empty($oldFile)){
                    $ancienFilename = $this->getParameter('imgFrise_directory') . $oldFile;
                    $filesystem= new Filesystem();
                    $filesystem->remove($ancienFilename);
                }

                $frise->setLien($newFilename);
            }
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', 'La frise a bien été modifié !');

            // Retour liste frise
            return $this->redirectToRoute('listefrise', [], Response::HTTP_SEE_OTHER);
        }
        elseif($form->isSubmitted()){
            $this->addFlash('error', 'Une erreur c\'est produite !');
        }

        // affichage du formulaire
        return $this->renderForm('commun/edit.html.twig', [
            'frise' => $frise,
            'form' => $form,
            'titre' => 'Modification',
            'titre2' => 'Modification Frise',
        ]);
    }

    /**
     * @Route("/sup/{id}", name="supfrise")
     */
    public function delete(Request $requete, Frise $frise): Response
    {
        // Autorise L'Admin
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        // si le token CRSF et present et conforme
        if ($this->isCsrfTokenValid('delete'.$frise->getId(), $requete->query->get('csrf'))) {
            $entityManager = $this->getDoctrine()->getManager();

            $oldFile = basename($frise->getLien());


            if(!empty($oldFile)){
                $ancienFilename = $this->getParameter('imgFrise_directory') . $oldFile;
                $filesystem= new Filesystem();
                $filesystem->remove($ancienFilename);
            }
            // mise en place de la requête indiquant que la donnée selectionnée doit être supprimée
            $entityManager->remove($frise);
            // exécution de la requête de "delete"
            $entityManager->flush();
            $this->addFlash('success', 'L\'élément a bien été modifié de la frise !');
        }
        else{
            $this->addFlash('error', 'Une erreur c\'est produite !');
        }

        // Retour liste frise
        return $this->redirectToRoute('listefrise', [], Response::HTTP_SEE_OTHER);
    }
}

templates/frise/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{titre}}{% endblock %}

{% block body %}
<main class="explo">
    <h1>Liste</h1>

    <div class="table">
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Titre</th>
                    <th>Contenu ?</th>
                    <th>Image ?</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for frise in frises %}
                <tr>
                    <td>{{ frise.date ? frise.date|date('Y') : '' }}</td>
                    <td>{{ frise.nom }}</td>
                    <td>{{ frise.contenu ? 'Oui' : '' }}</td>
                    <td>{{ frise.lien ? 'Oui' : '' }}</td>
                    <td>
                        <a class="none" onclick="return confirm('Es-tu sûr de vouloir supprimer cet élément?');" href="{{ path( 'supfrise', {'id': frise.id}) }}?csrf={{csrf_token('delete' ~ frise.id)}}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" class="bi bi-trash-fill trash" viewBox="0 0 16 16">
                                <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                            </svg>
                        </a>
                        <a class="none" href="{{ path('modiffrise', {'id': frise.id}) }}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" class="bi bi-gear-fill param" viewBox="0 0 16 16">
                                <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z"/>
                            </svg>
                        </a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="7">Aucun élément trouvé</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <h3><a class="ajout" href="{{ path('ajoutfrise') }}">Nouveau</a></h3>
    </div>

</main>
{% endblock %}

templates/frise/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{frise.titre}}{% endblock %}

{% block body %}

    <h1>Frise</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ frise.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ frise.date ? frise.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ frise.titre }}</td>
            </tr>
            <tr>
                <th>Contenu</th>
                <td>{{ frise.contenu }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ frise.image }}</td>
            </tr>
            <tr>
                <th>Id_div</th>
                <td>{{ frise.idDiv }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('listefrise') }}">back to list</a>

    <a href="{{ path('modiffrise', {'id': frise.id}) }}">edit</a>

    {{ include('frise/_delete_form.html.twig') }}
{% endblock %}