src/Entity/BanqueImage.php
<?php

namespace App\Entity;

use App\Repository\BanqueImageRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BanqueImageRepository::class)
 */
class BanqueImage
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lien;

    /**
     * @ORM\ManyToOne(targetEntity=Projet::class, inversedBy="banqueImages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_projet;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getLien(): ?string
    {
        return $this->lien;
    }

    public function setLien(string $lien): self
    {
        $this->lien = $lien;

        return $this;
    }

    public function getIdProjet(): ?Projet
    {
        return $this->id_projet;
    }

    public function setIdProjet(?Projet $id_projet): self
    {
        $this->id_projet = $id_projet;

        return $this;
    }
}

src/Form/UtilisateurType.php
<?php

namespace App\Form;

use App\Entity\Utilisateur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;


class UtilisateurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('nom', TextType::class, [
            'required' => false,
            ])
        ->add('prenom', TextType::class, [
            'required' => false,
            ])
        ->add('pseudo', TextType::class, [
            'required' => false,
            ])
        ->add('email', EmailType::class)
        ->add('lien', UrlType::class, [
            'required' => false,
            ])
        ->add('photo',FileType::class,[
            'attr' => ['rows'=>'10'],
            'required' => false,
            'mapped' => false,
            'label' => 'Logo (.PNG, .JPEG, .GIF, .SVG file)',
            'constraints' => [
                new File([
                    'maxSize' => '512k',
                    'mimeTypes' => [
                        'image/*',
                    ],
                ])
            ],

        ])
        ;
        foreach ($options['roles'] as $role){
            if($role == 'ROLE_ADMIN')
            {
                $builder
                /*->add('plainPassword', RepeatedType::class, [
                    'type' => PasswordType::class,
                    'first_options'  => [
                        'label' => 'Nouveau mot de passe',
                        'required' => false,
                        'constraints' => [
                            new NotBlank([
                                'message' => 'Veuillez entrer un mot de passe',
                            ]),
                            new Regex('/^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[$&+,:;=?@#|<>.^*()%!]).{12,}$/')
                        ],
                    ],
                    'second_options' => [
                        'label' => 'Confirmation du mot de passe',
                        'required' => false,
                    ],
                    'required' => false,
                    'mapped' => false,
                    'attr' => ['autocomplete' => 'new-password'],
                ])*/
                ->add('roles', ChoiceType::class, [
                    'label' => 'Rôles',
                    'choice_attr' => [
                        'Créateur' => ['class' => 'inputcheck'],
                        'Administrateur' => ['class' => 'inputcheck'],
                    ],
                    'multiple' => true,
                    'expanded' => true,
                    'required' => false,
                    'choices' => [
                        'Créateur' => 'ROLE_CREATEUR',
                        'Administrateur' => 'ROLE_ADMIN',
                    ]
                    ])
                ;
            }
        }

        $builder
        ->add('Modifier', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Utilisateur::class,
            'roles' => [0 => 'ROLE_USER'],
        ]);
    }
}

src/Controller/UtilisateurController.php
<?php

namespace App\Controller;

use App\Entity\Utilisateur;
use App\Form\ForgottenType;
use App\Form\UtilisateurType;
use App\Form\RegistrationFormType;
use App\Repository\BanqueImageRepository;
use App\Repository\UtilisateurRepository;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

/**
 * @Route("/utilisateur")
 */
class UtilisateurController extends AbstractController
{
    /**
     * @Route("/liste", name="listeutilisateurs")
     */
    public function index(UtilisateurRepository $utilisateurRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        return $this->render('utilisateur/index.html.twig', [
            'utilisateurs' => $utilisateurRepository->findAll(),
            'titre' => 'Liste Utilisateur'
        ]);
    }

    /**
     * @Route("/ajout", name="ajoututilisateur")
     */
    public function new(Request $request, UserPasswordHasherInterface  $userPasswordHasherInterface): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $utilisateur = new Utilisateur();
        $form = $this->createForm(RegistrationFormType::class, $utilisateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if(preg_match('/^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[$&+,:;=?@#|<>.^*()%!]).{12,}$/', $form->get('plainPassword')->getData()) === 0){
                $this->addFlash('error', 'Le mot de passe n\'est pas valide');
                return $this->renderForm('commun/new.html.twig', [
                    'utilisateur' => $utilisateur,
                    'form' => $form,
                    'titre' => 'Nouvel Utilisateur',
                ]);
            }

            $utilisateur->setPassword(
                $userPasswordHasherInterface->hashPassword(
                    $utilisateur,
                    $form->get('plainPassword')->getData()
                )
            );

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($utilisateur);
            $entityManager->flush();
            $this->addFlash('success', 'Un nouvel utilisateur a bien été ajouté !');
            return $this->redirectToRoute('accueil');
        }
        elseif($form->isSubmitted()){
            if(preg_match('/^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[$&+,:;=?@#|<>.^*()%!]).{12,}$/', $form->get('plainPassword')->getData()) === 0){
                $this->addFlash('error', 'Le mot de passe n\'est pas valide');
            }
            else{
                $this->addFlash('error', 'Une erreur c\'est produite !');
            }
        }

        return $this->renderForm('commun/new.html.twig', [
            'form' => $form,
            'titre' => 'Nouvel Utilisateur'

        ]);
    }

    /**
     * @Route("/details/{id}", name="detailsutilisateur")
     */

    public function show(Utilisateur $utilisateur, BanqueImageRepository $banqueImageRepository): Response
    {
        if($utilisateur->getId() != $this->getUser()->getId()){
            $this->addFlash('error', 'Vous n\'avez pas accès');
            return $this->redirectToRoute('accueil');
        }
        
        return $this->render('utilisateur/show.html.twig', [
            'utilisateur' => $utilisateur,
            'titre' => $utilisateur->getPseudo(),
            'projets' => $banqueImageRepository->findAllLogo($utilisateur->getId()),
        ]);

    }

    /**
     * @Route("/password/{id}", name="passwordutilisateur")
     */
    public function passwordU(Utilisateur $utilisateur, BanqueImageRepository $banqueImageRepository, Request $request, UserPasswordHasherInterface  $userPasswordHasherInterface): Response
    {

        if( $utilisateur->getId() != $this->getUser()->getId() || !$this->IsGranted('ROLE_ADMIN')){
            $this->addFlash('error', 'Vous n\'avez pas accès');
            return $this->redirectToRoute('accueil');
        }


        $form = $this->createForm(ForgottenType::class, $utilisateur, ['email' => $utilisateur->getEmail()]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            if(password_verify($form->get('ancien')->getData(), $utilisateur->getPassword())) {

                if(preg_match('/^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[$&+,:;=?@#|<>.^*()%!]).{12,}$/', $form->get('plainPassword')->getData()) === 0){
                    $this->addFlash('error', 'Le mot de passe n\'est pas valide');
                    return $this->renderForm('commun/new.html.twig', [
                        'utilisateur' => $utilisateur,
                        'form' => $form,
                        'titre' => 'Modification MDP',
                    ]);
                }

                $utilisateur->setPassword(
                    $userPasswordHasherInterface->hashPassword(
                        $utilisateur,
                        $form->get('plainPassword')->getData()
                    )
                );
            }
            else {
                $this->addFlash('error', 'Le mot de passe est incorrecte!');
                return $this->render('utilisateur/show.html.twig', [
                    'utilisateur' => $utilisateur,
                    'titre' => $utilisateur->getPseudo(),
                    'projets' => $banqueImageRepository->findAllLogo($utilisateur->getId()),
                ]);
            }

            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', 'L\'utilisateur a bien été modifié !');
            return $this->redirectToRoute('accueil');
        }
        elseif($form->isSubmitted()){
            $this->addFlash('error', 'Une erreur c\'est produite !');
        }


        return $this->render('commun/edit.html.twig', [
            'utilisateur' => $utilisateur,
            'form' => $form->createView(),
            'titre' => $utilisateur->getPseudo(),
            'titre2' => 'Modification du mot de passe',
        ]);

    }


    /**
     * @Route("/modif/{id}", name="modifutilisateur")
     */
    public function edit(Request $request, Utilisateur $utilisateur, SluggerInterface $slugger, UserInterface $user, UserPasswordHasherInterface  $userPasswordHasherInterface): Response
    {
        if($this->IsGranted('ROLE_ADMIN') || $utilisateur->getId() == $this->getUser()->getId()){

            $oldFile = basename($utilisateur->getPhoto());

            $form = $this->createForm(UtilisateurType::class, $utilisateur, ['roles' => $user->getRoles()]);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                /*if(!empty($form->get('plainPassword')->getData()) && preg_match('/^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[$&+,:;=?@#|<>.^*()%!]).{12,}$/', $form->get('plainPassword')->getData()) == 1){
                    $utilisateur->setPassword(
                        $userPasswordHasherInterface->hashPassword(
                            $utilisateur,
                            $form->get('plainPassword')->getData()
                        )
                    );
                }*/

                $lienFile = $form->get('photo')->getData();
                if (!empty($lienFile)) {
                    $originalFilename = pathinfo($lienFile->getClientOriginalName(), PATHINFO_FILENAME);
                    $safeFilename = $slugger->slug($originalFilename);
                    $newFilename = 'img/Utilisateur/'.$safeFilename.'-'.uniqid().'.'.$lienFile->guessExtension();

                    try {
                        $lienFile->move(
                            $this->getParameter('imgUtilisateur_directory'),
                            $newFilename
                        );
                    } catch (FileException $e) {
                        $this->addFlash('error', 'Le mouvement a échoué !');
                        return $this->redirectToRoute('accueil');
                    }

                    if(!empty($oldFile)){
                        $ancienFilename = $this->getParameter('imgFrise_directory') . $oldFile;
                        $filesystem= new Filesystem();
                        $filesystem->remove($ancienFilename);
                    }

                    $utilisateur->setPhoto($newFilename);
                }

                $this->getDoctrine()->getManager()->flush();
                $this->addFlash('success', 'L\'utilisateur a bien été modifié !');
                return $this->redirectToRoute('accueil');
            }
            elseif($form->isSubmitted()){
                $this->addFlash('error', 'Une erreur c\'est produite !');
            }
        }
        else{
            $this->addFlash('error', 'Vous n\'avez pas accès');
            return $this->redirectToRoute('accueil');
        }

        return $this->renderForm('commun/edit.html.twig', [
            'utilisateur' => $utilisateur,
            'form' => $form,
            'titre' => $utilisateur->getNom(),
            'titre2' => 'Modifier ' . $utilisateur->getNom() .' '. $utilisateur->getPrenom() ,
        ]);
    }

    /**
     * @Route("/sup/{id}", name="suputilisateur")
     */
    public function delete(Request $request, Utilisateur $utilisateur): Response
    {
        if($this->IsGranted('ROLE_ADMIN') || $utilisateur->getId() == $this->getUser()->getId){
        
            if ($this->isCsrfTokenValid('delete'.$utilisateur->getId(), $request->query->get('csrf'))) {
                $entityManager = $this->getDoctrine()->getManager();

templates/utilisateur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur index{% endblock %}

{% block body %}
    <h1>Utilisateur index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Email</th>
                <th>Roles</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Pseudo</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for utilisateur in utilisateurs %}
            <tr>
                <td>{{ utilisateur.email }}</td>
                <td>{{ utilisateur.roles ? utilisateur.roles|json_encode : '' }}</td>
                <td>{{ utilisateur.nom }}</td>
                <td>{{ utilisateur.prenom }}</td>
                <td>{{ utilisateur.pseudo }}</td>
                <td>
                    <a href="{{ path('utilisateur_show', {'id': utilisateur.id}) }}">show</a>
                    <a href="{{ path('utilisateur_edit', {'id': utilisateur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('utilisateur_new') }}">Create new</a>
{% endblock %}

templates/utilisateur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Utilisateur{% endblock %}

{% block body %}

<main class="explo">

    <h1>
        Bonjour, {{utilisateur.pseudo}}
        {% if is_granted('ROLE_ADMIN') or utilisateur.id == app.user.id %}
        <a class="none" onclick="return confirm('Es-tu sûr de vouloir supprimer cet élément?');" href="{{ path( 'suputilisateur', {'id': utilisateur.id}) }}?csrf={{csrf_token('delete' ~ utilisateur.id)}}">
            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" class="bi bi-trash-fill trash" viewBox="0 0 16 16">
                <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
            </svg>
        </a>
        <a class="none" href="{{ path('modifutilisateur', {'id': utilisateur.id}) }}">
            <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" class="bi bi-gear-fill param" viewBox="0 0 16 16">
                <path d="M9.405 1.05c-.413-1.4-2.397-1.4-2.81 0l-.1.34a1.464 1.464 0 0 1-2.105.872l-.31-.17c-1.283-.698-2.686.705-1.987 1.987l.169.311c.446.82.023 1.841-.872 2.105l-.34.1c-1.4.413-1.4 2.397 0 2.81l.34.1a1.464 1.464 0 0 1 .872 2.105l-.17.31c-.698 1.283.705 2.686 1.987 1.987l.311-.169a1.464 1.464 0 0 1 2.105.872l.1.34c.413 1.4 2.397 1.4 2.81 0l.1-.34a1.464 1.464 0 0 1 2.105-.872l.31.17c1.283.698 2.686-.705 1.987-1.987l-.169-.311a1.464 1.464 0 0 1 .872-2.105l.34-.1c1.4-.413 1.4-2.397 0-2.81l-.34-.1a1.464 1.464 0 0 1-.872-2.105l.17-.31c.698-1.283-.705-2.686-1.987-1.987l-.311.169a1.464 1.464 0 0 1-2.105-.872l-.1-.34zM8 10.93a2.929 2.929 0 1 1 0-5.86 2.929 2.929 0 0 1 0 5.858z"/>
            </svg>
        </a>
        {% endif %}
    </h1>

    <div class="flex ">
        <div class="profilUtilisateur1 profilUser">
            <h2>Profil</h2>
            {% if utilisateur.photo is not empty %}
                <div class ='photoUtilisateur'>
                    <img src="{{asset(utilisateur.photo)}}" alt="Photo invisible"/>
                </div>
            {% endif %}

            {% if utilisateur.nom is not empty %}
                <h3>Nom : {{ utilisateur.nom }}</h3>
            {% endif %}
            {% if utilisateur.prenom is not empty %}
                <h3>Prenom : {{ utilisateur.prenom }}</h3>
            {% endif %}
            {% if utilisateur.pseudo is not empty %}
                <h3>Pseudo : {{ utilisateur.pseudo }}</h3>
            {% endif %}
            <h3>Email : {{ utilisateur.email }}</h3>
            
            {% if utilisateur.pseudo is not empty %}
                <h3>Lien : <a href="{{utilisateur.lien}}" target="_blank">{{ utilisateur.lien }}</a></h3>
            {% endif %}

            <h3>Mot de passe : ------- <a href="{{path('passwordutilisateur',{id : utilisateur.id})}}">Modifier</a></h3>
        </div>
        
        <div class="profilUtilisateur2 profilUser">
            <h2>Projets</h2>
            {% for projet in projets %}
                <div class ='projetUtilisateur'>
                    <a href="{{path('detailprojet',{id : projet.idProjet})}}">
                        <img src="{{asset(projet.lienImage)}}" alt="{{projet.nomImage}} invisible"/>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</main>

{% endblock %}